services:
  - type: web
    name: student-portal
    env: python
    pythonVersion: "3.11.9"
    buildCommand: pip install --break-system-packages -r requirements.txt
    startCommand: python -m gunicorn app:app